### PR TITLE
Challenge 306 intermediate

### PR DESCRIPTION
**Pull request by pskinnunen**
Ok, here's the new pull for 306 challenge

### CODE REVIEW

**Comment by jwmarcus** [comment]
A couple things here.

You can delete the README.txt file, as it's not supposed to be there.

**Comment by pskinnunen** [comment]
That's one thing.

**Comment by jwmarcus** [comment]
I'm not following you. There is a readme.txt and a readme.md. You should have one (preferably the .md one). You may have removed it locally, but you need to ```git rm README.txt``` then ```git commit -m 'Removing duplicate README file'```, then ```git push origin master```.

**Comment by jwmarcus** [comment]
Also, you will want to start naming your PR's better. Like "Challenge 306 Intermediate" instead of the "initial commit." Furthermore, your only "initial commit" was the one you did when you originally created the repository. Anything after that needs to be more descriptive.

**Comment by jwmarcus** [comment]
Aside from that, it seems to work. Go ahead and fix that and merge. 

How about taking on something harder next? https://www.reddit.com/r/dailyprogrammer/comments/6g8ey0/20170609_challenge_318_hard_ladder_logic/

Also, you should fork and enhance someone elses code now. Try forking my repo for the Indico neural network library: https://github.com/jwmarcus/indico-harness 

Make it so you can automatically prompt for an image URL and then determine if what type of dog is in the photo.

**Comment by pskinnunen** [comment]
was poking fun you said a couple things here and only mentioned one.

I'll get that cleaned out tonight.

**Comment by jwmarcus** [comment]
Oh, you're a funny one.

**Pull request merged**
