### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by pskinnunen**
This is the initial development for challenge 300.

### CODE REVIEW

**Comment by jwmarcus** [comment]
A few things here:

1. the winsound package is for windows only. That's no good because many developers use Macs and even Linux. Please try to find something agnostic to the platform.
2. There is no Python requirements file. Here is how you can set one up:

```pip3 freeze > requirements.pip```

This will dump the currently installed python packages into a file called requirements.pip, where other users can use: 

```pip3 install -r requirements.pip```

... and be on their merry way.

3. That one-liner is a bit messy. I also don't think you need the math package for it. Try breaking it up into a few lines like:

```freq_num = 2 ** (step / 12) # Notes are 1/12 of a decade per half step```
```freq_num_int = int(freq_num) # Notwinsound package can only take integers```
```notwinsound.Beep(freq_num_int, 1000) # Play sound for 1 second```

**Comment by pskinnunen** [comment]
This has been updated to match what you were suggesting.  I found a method that should work for non-windows but wasn't the most impressed with it so ended up also taking a solution to writing the output into a wave file as well.

**Comment by jwmarcus** [comment]
It looks like requirements.pip is empty. 

```0 lines (0 sloc)  0 Bytes```

Try activating the virtaulenv first before "freezing" to the file.

**Comment by jwmarcus** [comment]
wave_write.py works beautifully. Maybe take it down to ```FREQUENCY = 220``` next time ;) 

This code ran beautifully without requirements, so maybe use this instead of the previous main.py. Be sure to add in another commit to this branch and send me back that PR!

Keep up the good work!

**Comment by pskinnunen** [comment]
Ok, so for this current pull what should I do?

Should I just dump the original main.py and do another push? 

Not sure what the correct approach is.

**Comment by jwmarcus** [comment]
I would say to edit main.py to meet the task needs. Then recommit the file
(it will be almost 100% changes) and resubmit the PR

**Comment by pskinnunen** [comment]
Ok, then should this PR be closed out then or once I recommit the change it will be reflected in the PR?

**Comment by jwmarcus** [comment]
When you commit (with some new message) it will be added to the pull
request timeline. You can have multiple commits in a PR. It's also good
practice to show your work over time.

**Comment by pskinnunen** [comment]
Ok, was thrown off when you said resubmit the PR.

I figured I did it correctly last night but wasn't sure.

**Comment by pskinnunen** [comment]
Ok, pushed again.

Now, if I wanted to start another branch before this pull is merged, would I change back to the master first then start a new branch?

What is the best way to do that because I think that is what I messed up last time around.

**Comment by jwmarcus** [comment]
Great question!

First, commit any work you have to the branch you are in. You can also
temporarily push your work to a temporary stack via "git stash"

Next, change back to master via git checkout master.

Then, branch off of master with git branch newBranch then git checkout new
branch.

If you branch while in a branch, you will create a branch that contains all
the changes from the branch you started in. If you are working on really
big features (like and entire module) this might be desired behavior. For
example, if you are building a huge authentication module you might break
it up into front end and back end, which could each have their own sub
branches.

**Comment by jwmarcus** [comment]
This still does not run.

    Traceback (most recent call last):
    File "main.py", line 22, in <module>
      main()
    File "main.py", line 19, in main
      winsound.Beep(freq_int,1000)
    NameError: name 'winsound' is not defined

Because there is no requirements.pip file, I'm assuming you are relying on the system libraries.

The way you are working around the system requirement is kind of wonky too. This exercise might seem trivial, but I assure you getting things to work cross platform is a PITA, which is pretty much the new goal of this exercise. Take a step back before you make your next commit:

First, determine which platform you're playing on:

```
try:
    import winsound
    platform = "win"
except ImportError:
    print("winsound lib not found, must not be a windows machine")

try:
    import os
    platform = "osx"
except ImportError:
    print("os lib not found, must not be a mac")

if platform == None
    raise RuntimeError("CRIT: Unsupported System Detected")
```

Next, use an if statement inside of play_sound(f, d) based on this variable:

```
if platform is "osx":
    os.system...
elif platform is "win":
    winsound...
else:
    raise RuntimeError("CRIT: How did you get here? I thought I checked for system type?")
```

Also, please look into using a linter. As your spacing is all off.  Try this guy: http://pep8online.com/

```
freq_num = (2**(step/12))*a_frequency
```

Should be something like:

```
freq_num = (2 ** (step / 12)) * a_frequency
```

This is your new grammar bible: https://www.python.org/dev/peps/pep-0008/#other-recommendations

**Comment by pskinnunen** [comment]
Ok, apparently the changes I made to the Main.py didn't get pushed and now they should be there.

**Comment by jwmarcus** [comment]
main.py is cheating. You just switched to output a file.

Also, your indentation is not consistent. Some lines have 2 spaces, other 4. In Python, we prefer 4 spaces. And if you mention anything about tabs out-loud someone will likely hit you with a tire iron.

Let's wrap this guy up and get some more challenges done. I have ideas for a web app you should build, too.

**Comment by pskinnunen** [comment]
Also, technically it is not cheating using a file.  It was a bonus objective so there.

**Comment by jwmarcus** [comment]
This looks good.

Go ahead and merge to master, then delete the branch and let's eat started
on the next one!

**Pull request merged**
